import { CaseRecord, EntityRecord, RelationshipRecord, EmergingNetwork, User } from '../src/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-01',
    name: 'Inspector Kabir Rathore',
    badgeId: 'DL-CR-4409',
    rank: 'Inspector of Police',
    department: 'Crime Branch / Special Cell (Delhi-NCR)',
    role: 'Investigator',
  },
  {
    id: 'USR-02',
    name: 'ACP Sunita Verma',
    badgeId: 'DL-IPS-1092',
    rank: 'Assistant Commissioner of Police',
    department: 'Cyber Crime & Intelligence Fusion Centre',
    role: 'Senior Analyst',
  },
  {
    id: 'USR-03',
    name: 'Sub-Inspector Rohit Malik',
    badgeId: 'HR-STF-3011',
    rank: 'Sub-Inspector',
    department: 'Special Task Force (Gurgaon Unit)',
    role: 'Investigator',
  }
];

export const INITIAL_CASES: CaseRecord[] = [
  {
    id: 'CASE-101',
    firNumber: 'FIR-2026/DL-101',
    title: 'Interstate Luxury SUV Theft & Chassis Tampering',
    crimeType: 'Vehicle Theft',
    date: '2026-02-12',
    location: 'Cyber Hub, Sector 29, Gurgaon',
    city: 'Gurgaon',
    coordinates: [28.4595, 77.0266],
    description: 'Complainant reported theft of Toyota Fortuner with fake number plate. Suspect intercepted on CCTV with accomplice Rahul Sharma. A burner phone 9876543210 was used to coordinate getaway vehicle DL01AB1234 towards Mehrauli border.',
    status: 'Active',
    priority: 'Critical',
    assignedOfficer: 'Inspector Kabir Rathore',
    entities: {
      persons: ['Rahul Sharma', 'Sunil Gujjar'],
      phones: ['9876543210', '9811223344'],
      vehicles: ['DL01AB1234', 'HR26DQ4421'],
      locations: ['Gurgaon', 'Mehrauli Delhi'],
      financials: ['rahul@upi'],
      organizations: ['Apex Auto Logistics']
    },
    detectedConnectionsCount: 4,
    notes: 'Primary suspect fled towards Delhi. Shared vehicle plate with FIR-102 & FIR-127.'
  },
  {
    id: 'CASE-102',
    firNumber: 'FIR-2026/DL-102',
    title: 'High-Value Digital Extortion & Impersonation',
    crimeType: 'Cyber Fraud / UPI',
    date: '2026-02-21',
    location: 'Connaught Place, Central Delhi',
    city: 'Delhi',
    coordinates: [28.6304, 77.2177],
    description: 'Corporate executive received extortion threats demanding ₹25 Lakhs. Suspect Amit Kumar communicated using phone 9876543210 and demanded payments to rahul@upi. Getaway car identified as DL01AB1234 seen exiting Barakhamba Road.',
    status: 'Active',
    priority: 'High',
    assignedOfficer: 'ACP Sunita Verma',
    entities: {
      persons: ['Amit Kumar', 'Rahul Sharma'],
      phones: ['9876543210', '9910022334'],
      vehicles: ['DL01AB1234'],
      locations: ['Connaught Place Delhi', 'Barakhamba Road'],
      financials: ['rahul@upi', 'amit.kumar@okhdfcbank'],
      organizations: ['CyberShield Shielding Services']
    },
    detectedConnectionsCount: 5,
    notes: 'Shares phone and getaway vehicle directly with Case 101. Occurred 9 days apart.'
  },
  {
    id: 'CASE-104',
    firNumber: 'FIR-2026/UP-104',
    title: 'Organized Vehicle Chopping Ring & Forged RC Racket',
    crimeType: 'Vehicle Theft',
    date: '2026-03-05',
    location: 'Sector 62, Industrial Area, Noida',
    city: 'Noida',
    coordinates: [28.6280, 77.3649],
    description: 'Raid on clandestine garage in Noida recovered stolen engine blocks and fake registration certificates. Suresh Yadav and Amit Kumar were caught operating stolen getaway car DL01AB1234. Contact number 9811223344 saved as "Boss Delhi".',
    status: 'Active',
    priority: 'High',
    assignedOfficer: 'Sub-Inspector Rohit Malik',
    entities: {
      persons: ['Suresh Yadav', 'Amit Kumar', 'R. Sharma'],
      phones: ['9811223344', '9899112233'],
      vehicles: ['DL01AB1234', 'UP16BF8899'],
      locations: ['Noida Sector 62', 'Mayur Vihar'],
      financials: ['suresh.yadav@paytm'],
      organizations: ['Star Spares Garage']
    },
    detectedConnectionsCount: 4,
    notes: 'Direct physical link to vehicle DL01AB1234 and accomplice Amit Kumar.'
  },
  {
    id: 'CASE-117',
    firNumber: 'FIR-2026/HR-117',
    title: 'Unaccounted Cash Transit & Hawala Channel',
    crimeType: 'Hawala / Money Laundering',
    date: '2026-03-18',
    location: 'Bata Chowk, Faridabad',
    city: 'Faridabad',
    coordinates: [28.3842, 77.3082],
    description: 'Interception of white Creta HR26DQ4421 carrying ₹1.4 Crore unaccounted cash. Courier Vikas Dubey confessed taking instructions over encrypted call from 9876543210. Funds routed through UPI ID amit.kumar@okhdfcbank.',
    status: 'Active',
    priority: 'Critical',
    assignedOfficer: 'Inspector Kabir Rathore',
    entities: {
      persons: ['Vikas Dubey', 'Rahul S.', 'Amit Kumar'],
      phones: ['9876543210', '9717788990'],
      vehicles: ['HR26DQ4421'],
      locations: ['Faridabad', 'Gurgaon Expressway'],
      financials: ['amit.kumar@okhdfcbank'],
      organizations: ['Shree Om Enterprises']
    },
    detectedConnectionsCount: 6,
    notes: 'Connects Case 101 phone with Case 102 UPI account. Financial backbone lead.'
  },
  {
    id: 'CASE-127',
    firNumber: 'FIR-2026/DL-127',
    title: 'Armed Logistics Cash Van Interception & Robbery',
    crimeType: 'Armed Robbery',
    date: '2026-02-25',
    location: 'Outer Ring Road, Rohini, Delhi',
    city: 'Delhi',
    coordinates: [28.7159, 77.1130],
    description: 'Armed heist targeting cash van. Surveillance footage tracked black Scorpio DL01AB1234 and active SIM ping from 9876543210 at crime scene. Suspect Rahul Kumar Sharma spotted fleeing towards Gurgaon.',
    status: 'Active',
    priority: 'Critical',
    assignedOfficer: 'Inspector Kabir Rathore',
    entities: {
      persons: ['Rahul Kumar Sharma', 'Sunil Gujjar', 'Vikas Dubey'],
      phones: ['9876543210', '9811002211'],
      vehicles: ['DL01AB1234', 'DL04XY9988'],
      locations: ['Rohini Delhi', 'Gurgaon'],
      financials: ['rahul@upi'],
      organizations: ['Apex Auto Logistics']
    },
    detectedConnectionsCount: 6,
    notes: 'Case 101 and Case 127 overlap: Same phone (9876543210), same vehicle (DL01AB1234), same locations, 13 days apart.'
  },
  {
    id: 'CASE-130',
    firNumber: 'FIR-2026/UP-130',
    title: 'Bulk POS & Fraudulent Pre-Activated SIM Consortium',
    crimeType: 'Cyber Fraud / UPI',
    date: '2026-04-02',
    location: 'Raj Nagar District Centre, Ghaziabad',
    city: 'Ghaziabad',
    coordinates: [28.6692, 77.4538],
    description: 'Cellular audit revealed 1,200 SIM cards issued on forged Aadhaar documents. Vikram Singh arrested with 40 active cards including 9811223344. Suspect admitted providing disposable numbers to Suresh Yadav syndicate.',
    status: 'Active',
    priority: 'Medium',
    assignedOfficer: 'ACP Sunita Verma',
    entities: {
      persons: ['Vikram Singh', 'Suresh Yadav'],
      phones: ['9811223344', '9899112233'],
      vehicles: ['UP14AZ2020'],
      locations: ['Ghaziabad', 'Noida Sector 62'],
      financials: ['vikram.pos@paytm'],
      organizations: ['Apex Tech Logistics', 'TeleLink Services']
    },
    detectedConnectionsCount: 3,
    notes: 'Technical feeder syndicate providing burner SIMs across Noida and Delhi.'
  },
  {
    id: 'CASE-135',
    firNumber: 'FIR-2026/DL-135',
    title: 'Interstate Contraband Smuggling via Concealed Cargo',
    crimeType: 'Narcotics',
    date: '2026-04-19',
    location: 'Mahipalpur Flyover, South West Delhi',
    city: 'Delhi',
    coordinates: [28.5444, 77.1278],
    description: 'Consignment of 4.5kg synthetic contraband seized from customized commercial van. Driver Deepak Chauhan stated cargo was booked by Suresh Yadav through Apex Auto Logistics using phone 9910022334.',
    status: 'Active',
    priority: 'High',
    assignedOfficer: 'Inspector Kabir Rathore',
    entities: {
      persons: ['Deepak Chauhan', 'Suresh Yadav', 'Sunil Gujjar'],
      phones: ['9910022334', '9871122334'],
      vehicles: ['DL04XY9988', 'HR55AC7711'],
      locations: ['Mahipalpur Delhi', 'Gurgaon'],
      financials: ['deepak.trans@axl'],
      organizations: ['Apex Auto Logistics']
    },
    detectedConnectionsCount: 4,
    notes: 'Apex Auto Logistics appears across vehicle theft and narcotics shipments.'
  },
  {
    id: 'CASE-140',
    firNumber: 'FIR-2026/DL-140',
    title: 'Investment Phishing & Mules Account Network',
    crimeType: 'Cyber Fraud / UPI',
    date: '2026-05-08',
    location: 'Nehru Place IT Hub, South Delhi',
    city: 'Delhi',
    coordinates: [28.5492, 77.2533],
    description: 'Victims cheated of ₹85 Lakhs through fake stock trading bot. Substantial proceeds credited to UPI account amit.kumar@okhdfcbank and subsequently layered via crypto swaps through Manoj Khandelwal.',
    status: 'Active',
    priority: 'High',
    assignedOfficer: 'ACP Sunita Verma',
    entities: {
      persons: ['Manoj Khandelwal', 'Amit Kumar', 'Pooja Hegde'],
      phones: ['9910022334', '9810102030'],
      vehicles: ['DL08CC4567'],
      locations: ['Nehru Place Delhi', 'Noida'],
      financials: ['amit.kumar@okhdfcbank', 'manoj.invest@icici'],
      organizations: ['FinFuture Advisory LLC']
    },
    detectedConnectionsCount: 5,
    notes: 'Shares the key UPI account from Case 102 and Case 117.'
  },
  {
    id: 'CASE-145',
    firNumber: 'FIR-2026/HR-145',
    title: 'Commercial Construction Extortion & Threat Calls',
    crimeType: 'Extortion',
    date: '2026-05-24',
    location: 'Golf Course Extension Road, Gurgaon',
    city: 'Gurgaon',
    coordinates: [28.4111, 77.0850],
    description: 'Real estate developer threatened with firing at site office unless ₹50 Lakh extortion paid. Caller identified himself as associate of Sunil Gujjar using phone 9811002211, last triangulated near Rohini.',
    status: 'Active',
    priority: 'Critical',
    assignedOfficer: 'Sub-Inspector Rohit Malik',
    entities: {
      persons: ['Sunil Gujjar', 'Vikas Dubey'],
      phones: ['9811002211', '9876543210'],
      vehicles: ['HR26DQ4421'],
      locations: ['Gurgaon Golf Course', 'Rohini Delhi'],
      financials: ['sguijjar@upi'],
      organizations: ['Apex Auto Logistics']
    },
    detectedConnectionsCount: 5,
    notes: 'Directly linked to Rohini shooter network and cash courier Vikas Dubey.'
  },
  {
    id: 'CASE-150',
    firNumber: 'FIR-2026/DL-150',
    title: 'Counterfeit Luxury Auto Registration Fraud',
    crimeType: 'Vehicle Theft',
    date: '2026-06-11',
    location: 'RTO Janakpuri, West Delhi',
    city: 'Delhi',
    coordinates: [28.6219, 77.0878],
    description: 'Internal audit detected forged NOC certificates for 14 stolen vehicles re-registered with altered VINs. RTO middleman named Manoj Khandelwal and Suresh Yadav as frequent submitters of dossiers.',
    status: 'Active',
    priority: 'Medium',
    assignedOfficer: 'Inspector Kabir Rathore',
    entities: {
      persons: ['Manoj Khandelwal', 'Suresh Yadav', 'Vikram Singh'],
      phones: ['9899112233', '9810102030'],
      vehicles: ['UP16BF8899', 'DL08CC4567'],
      locations: ['Janakpuri Delhi', 'Noida Sector 62'],
      financials: ['suresh.yadav@paytm'],
      organizations: ['Star Spares Garage']
    },
    detectedConnectionsCount: 4,
    notes: 'Connects Noida chopping ring to money laundering intermediary Manoj Khandelwal.'
  },
  {
    id: 'CASE-155',
    firNumber: 'FIR-2026/RJ-155',
    title: 'Interstate Stolen Vehicle Disposal Junction',
    crimeType: 'Vehicle Theft',
    date: '2026-06-29',
    location: 'Transport Nagar, Jaipur',
    city: 'Jaipur',
    coordinates: [26.9024, 75.8457],
    description: 'Highway patrol stopped car carrier carrying stolen Delhi vehicles. Bill of lading originated from Apex Auto Logistics, signed by Deepak Chauhan with recipient listed as Manoj Khandelwal.',
    status: 'Active',
    priority: 'Medium',
    assignedOfficer: 'Sub-Inspector Rohit Malik',
    entities: {
      persons: ['Deepak Chauhan', 'Manoj Khandelwal', 'Rahul Sharma'],
      phones: ['9871122334', '9810102030'],
      vehicles: ['HR55AC7711', 'DL01AB1234'],
      locations: ['Jaipur', 'Gurgaon'],
      financials: ['deepak.trans@axl'],
      organizations: ['Apex Auto Logistics']
    },
    detectedConnectionsCount: 5,
    notes: 'Proves vehicle DL01AB1234 was transferred through interstate transport network.'
  },
  {
    id: 'CASE-160',
    firNumber: 'FIR-2026/DL-160',
    title: 'Phishing Call Centre Bust & VoIP Spoofing',
    crimeType: 'Cyber Fraud / UPI',
    date: '2026-07-14',
    location: 'Okhla Phase 3, South Delhi',
    city: 'Delhi',
    coordinates: [28.5355, 77.2732],
    description: 'Raid on illegal call centre posing as international law enforcement. 24 systems confiscated. Operating manager Pooja Hegde revealed payroll disbursed via UPI from amit.kumar@okhdfcbank.',
    status: 'Active',
    priority: 'High',
    assignedOfficer: 'ACP Sunita Verma',
    entities: {
      persons: ['Pooja Hegde', 'Amit Kumar', 'Vikram Singh'],
      phones: ['9910022334', '9811223344'],
      vehicles: ['UP14AZ2020'],
      locations: ['Okhla Delhi', 'Ghaziabad'],
      financials: ['amit.kumar@okhdfcbank', 'pooja.hegde@axl'],
      organizations: ['FinFuture Advisory LLC', 'TeleLink Services']
    },
    detectedConnectionsCount: 6,
    notes: 'Ties together Amit Kumar financial accounts with SIM supplier Vikram Singh.'
  },
  {
    id: 'CASE-165',
    firNumber: 'FIR-2026/DL-165',
    title: 'Daylight Armed Heist at Jewellery Showroom',
    crimeType: 'Armed Robbery',
    date: '2026-08-01',
    location: 'Chandni Chowk, Old Delhi',
    city: 'Delhi',
    coordinates: [28.6506, 77.2303],
    description: 'Four masked assailants looted 2.8kg gold jewellery. CCTV tracked getaway motorcycle and backup SUV DL04XY9988. Suspect Sunil Gujjar identified through biometric facial match.',
    status: 'Active',
    priority: 'Critical',
    assignedOfficer: 'Inspector Kabir Rathore',
    entities: {
      persons: ['Sunil Gujjar', 'Rahul Kumar Sharma'],
      phones: ['9811002211', '9876543210'],
      vehicles: ['DL04XY9988'],
      locations: ['Chandni Chowk Delhi', 'Rohini Delhi'],
      financials: ['sguijjar@upi'],
      organizations: ['Apex Auto Logistics']
    },
    detectedConnectionsCount: 4,
    notes: 'Sunil Gujjar and Rahul Sharma coordinated via burner phone 9876543210.'
  },
  {
    id: 'CASE-170',
    firNumber: 'FIR-2026/HR-170',
    title: 'Highway Armed Truck Hijack & Electronic Cargo Theft',
    crimeType: 'Armed Robbery',
    date: '2026-08-16',
    location: 'Kundli-Manesar-Palwal Expressway, Gurgaon',
    city: 'Gurgaon',
    coordinates: [28.3588, 76.9405],
    description: 'Container truck laden with mobile chipsets hijacked at gunpoint. Hijackers used vehicle HR26DQ4421. Driver Vikas Dubey previously detained in Faridabad cash transit FIR-117 was recognized.',
    status: 'Active',
    priority: 'Critical',
    assignedOfficer: 'Sub-Inspector Rohit Malik',
    entities: {
      persons: ['Vikas Dubey', 'Sunil Gujjar', 'Suresh Yadav'],
      phones: ['9717788990', '9811002211'],
      vehicles: ['HR26DQ4421', 'HR55AC7711'],
      locations: ['KMP Expressway', 'Faridabad'],
      financials: ['suresh.yadav@paytm'],
      organizations: ['Star Spares Garage']
    },
    detectedConnectionsCount: 5,
    notes: 'Vikas Dubey and Sunil Gujjar escalated to high-value highway heists.'
  },
  {
    id: 'CASE-175',
    firNumber: 'FIR-2026/DL-175',
    title: 'Synthetic Meth Lab Operation & Darknet Mailings',
    crimeType: 'Narcotics',
    date: '2026-08-28',
    location: 'DLF Phase 3, Gurgaon Border',
    city: 'Gurgaon',
    coordinates: [28.4900, 77.0980],
    description: 'Premises searched on tip-off. Recovered packaging materials, domestic courier receipts handled by Deepak Chauhan. Suspect admitted payments received in crypto and converted via rahul@upi.',
    status: 'Active',
    priority: 'High',
    assignedOfficer: 'Inspector Kabir Rathore',
    entities: {
      persons: ['Deepak Chauhan', 'Rahul Sharma', 'Pooja Hegde'],
      phones: ['9871122334', '9876543210'],
      vehicles: ['DL01AB1234'],
      locations: ['Gurgaon DLF', 'Okhla Delhi'],
      financials: ['rahul@upi'],
      organizations: ['Apex Auto Logistics']
    },
    detectedConnectionsCount: 5,
    notes: 'Demonstrates deep convergence of auto theft, narcotics transport, and digital escrow.'
  }
];

export const INITIAL_EMERGING_NETWORKS: EmergingNetwork[] = [
  {
    id: 'NET-023',
    name: 'Interstate NCR Vehicle Theft & Hawala Nexus',
    casesCount: 15,
    personsCount: 11,
    phonesCount: 7,
    vehiclesCount: 6,
    locationsCount: 9,
    alertLevel: 'CRITICAL',
    growthVelocity30Days: '+5 new cases, 3 shared phones, 2 shared vehicles in past 30 days',
    description: 'An interconnected syndicate spanning Gurgaon, Delhi, Noida, and Faridabad operating organized vehicle theft, cash logistics heists, and laundering illicit proceeds via compromised UPI IDs.',
    lastActivity: '2026-08-28',
    keyEntities: ['Rahul Sharma', 'Amit Kumar', 'DL01AB1234', '9876543210', 'rahul@upi', 'HR26DQ4421'],
    suspectedNexus: 'Auto-theft logistics coupled with digital cyber extortion cashout channel'
  },
  {
    id: 'NET-014',
    name: 'NCR Pre-Activated SIM & Call-Centre Escrow Consortium',
    casesCount: 6,
    personsCount: 5,
    phonesCount: 4,
    vehiclesCount: 2,
    locationsCount: 4,
    alertLevel: 'HIGH',
    growthVelocity30Days: '+3 cases, 2 shared financial accounts',
    description: 'Wholesale acquisition of forged KYC SIM cards in Ghaziabad feeding fake stock investment centres in Okhla and Nehru Place.',
    lastActivity: '2026-08-16',
    keyEntities: ['Vikram Singh', 'Pooja Hegde', 'Amit Kumar', 'amit.kumar@okhdfcbank', '9811223344'],
    suspectedNexus: 'Cyber financial infrastructure feeding multi-district fraud'
  }
];
